train:
  data_path: data/labeled/comments.csv
  model_path: models/lr_model.pkl
  vectorizer_path: models/tfidf_vectorizer.pkl
  test_size: 0.2
  random_state: 42
  max_features: 20000
  ngram_range: [1, 2]

mlflow:
  experiment_name: sentiment_analysis

pipeline:
  run_prep: true
  run_train: true
  run_api: true

inference:
  host: 0.0.0.0
  port: 8000