experiments:
  - name: exp_lr_big
    dataset_path: data/labeled/_comments.csv
    preprocessing: lemmatized
    model_type: logreg
    vectorizer: tfidf
    max_features: 20000
    ngram_range: [1, 2]

  - name: exp_lr_small
    dataset_path: data/labeled/_comments.csv
    preprocessing: lemmatized
    model_type: logreg
    vectorizer: tfidf
    max_features: 5000
    ngram_range: [1, 2]

  - name: exp_nb
    dataset_path: data/labeled/comments.csv
    preprocessing: none
    model_type: nb
    vectorizer: count
    max_features: 10000
    ngram_range: [1, 2]

mlflow:
  experiment_name: sentiment_analysis

output_dir: models

train:
  data_path: data/labeled/_comments.csv
  model_path: models/exp_lr_big_model.pkl
  vectorizer_path: models/exp_lr_big_vectorizer.pkl
  test_size: 0.2
  random_state: 42
  max_features: 20000
  ngram_range: [1, 2]

pipeline:
  run_prep: true
  run_train: true
  run_api: true

inference:
  host: 0.0.0.0
  port: 8000