train:
  data_path: data/labeled/comments.csv
  text_column: clean_text
  target_column: sentiment

  model_dir: models/
  model_path: models/lr_model.pkl
  vectorizer_path: models/tfidf_vectorizer.pkl

  test_size: 0.2
  random_state: 42

mlflow:
  experiment_name: vk_sentiment_baseline

inference:
  host: 0.0.0.0
  port: 8000
